server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: springboot-microservice
            client-secret: L7CYws3HULROIAsA4aSwssvZZrS9iz10
            scope: openid, profile, read
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/springboot-microservice
        provider:
          keycloak:
            issuer-uri: http://localhost:8091/realms/Demo-Realm
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8091/realms/Demo-Realm
          jwk-set-uri: http://localhost:8091/realms/Demo-Realm/protocol/openid-connect/certs
springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /swagger-ui.html
  oAuthFlow:
    authorizationUrl: http://localhost:8091/realms/Demo-Realm/protocol/openid-connect/auth
    tokenUrl: http://localhost:8091/realms/Demo-Realm/protocol/openid-connect/token